language: php

sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*

before_install:
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/symfony=$SYMFONY_VERSION"; fi

install: composer update --prefer-source

script:
  - vendor/bin/phpunit -c phpunit.xml.dist

